/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fpliu_calendar_for_the_aged_Calendar */

#ifndef _Included_com_fpliu_calendar_for_the_aged_Calendar
#define _Included_com_fpliu_calendar_for_the_aged_Calendar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fpliu_calendar_for_the_aged_Calendar
 * Method:    getDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_calendar_1for_1the_1aged_Calendar_getDate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
