name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - run: ./gradlew assembleRelease
